title: Pir치ti T치bor
default_locale: "cs"
permalink: pretty
markdown: kramdown
facebookurl: https://www.facebook.com/piratitabor
logo: /static/logo.png
gems:
  - jekyll-sitemap
  - i18n
paginate: 7
paginate_path: "/clanky/:num/"
keywords: t치bor,pir치ti
url: https://tabor.pirati.cz

# see. best practices DOs and DONTs for details about following section
# http://www.elegantthemes.com/blog/tips-tricks/best-practices-for-using-categories-and-tags-in-wordpress
avail_tags: transparence, it, kultura, sport, jordan, krizikac, web
avail_cats: AKCE, JEDNANI, CLANKY
avail_filecats: SMLOUVY, ZAPISY, VYKRESY, GRAFIKA
